[colors.bright]
black = "#6D7070"
blue = "#1BA6FA"
cyan = "#73FBF1"
green = "#B8E466"
magenta = "#A578EA"
red = "#FF4352"
white = "#FEFEF8"
yellow = "#FFD750"

# [colors.cursor]
# text = "#FF261E"
# cursor = "#FF261E"

[colors.normal]
black = "#0d0d0d"
blue = "#1BA6FA"
cyan = "#21DEEF"
green = "#A0E521"
magenta = "#8763B8"
red = "#FF301B"
white = "#EBEBEB"
yellow = "#FFC620"

[colors.primary]
background = "#292C3E"
foreground = "#EBEBEB"

[cursor]
thickness = 0.25

[font.normal]
style = "Bold"

[[hints.enabled]]
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.command]
args = ["/c", "start", ""]
program = "cmd"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[[mouse.bindings]]
action = "ClearSelection"
mouse = "Right"

[selection]
save_to_clipboard = true
