".vimrc file - Save this file as .vimrc in your home directory. (e.g. /home/user/.vimrc)

""Generated by vimrcgenerator.appspot.com
"Author: Robert Pyke


"-- General --
set nocompatible
set ruler		"Show the line and column number of the cursor position

"-- Programming --
set autoindent		"Copy indent from current line when starting a new line
set smartindent		"Do smart indenting when starting a new line. Works with supported c-like languages

"-- Spaces/Tabs --
set noexpandtab		"Strictly use tabs when tab is pressed (this is the default)
set shiftwidth=4
set tabstop=4

"-- Searching --
set hlsearch		"Highlight search results
set ignorecase		"When doing a search, ignore the case of letters
set smartcase		"Override the ignorecase option if the search pattern contains upper case letters
set incsearch
set wrapscan		"Wraps around to other end of file when searching

"-- Tabbed Editing --

""-- Tweaks --
"Add tweak for better backspace support
set backspace=indent,eol,start
